/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:8e12561846cc5d31a7af99b15517ed24:55e0fb98ae84b3483af7cef979a43be0:62638a7907f67844717c23f8fe57e0ea$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class Notes
	{
		public const string ArrowDOWN0000 = "arrowDOWN0000";
		public const string ArrowLEFT0000 = "arrowLEFT0000";
		public const string ArrowRIGHT0000 = "arrowRIGHT0000";
		public const string ArrowUP0000 = "arrowUP0000";
		public const string Blue_hold_end0000 = "blue hold end0000";
		public const string Blue_hold_piece0000 = "blue hold piece0000";
		public const string Blue0000 = "blue0000";
		public const string Down_confirm0000 = "down confirm0000";
		public const string Down_confirm0001 = "down confirm0001";
		public const string Down_confirm0002 = "down confirm0002";
		public const string Down_confirm0003 = "down confirm0003";
		public const string Down_press0000 = "down press0000";
		public const string Down_press0001 = "down press0001";
		public const string Down_press0002 = "down press0002";
		public const string Down_press0003 = "down press0003";
		public const string Green_hold_end0000 = "green hold end0000";
		public const string Green_hold_piece0000 = "green hold piece0000";
		public const string Green0000 = "green0000";
		public const string Left_confirm0000 = "left confirm0000";
		public const string Left_confirm0001 = "left confirm0001";
		public const string Left_confirm0002 = "left confirm0002";
		public const string Left_confirm0003 = "left confirm0003";
		public const string Left_press0000 = "left press0000";
		public const string Left_press0001 = "left press0001";
		public const string Left_press0002 = "left press0002";
		public const string Left_press0003 = "left press0003";
		public const string Purple_hold_end0000 = "purple hold end0000";
		public const string Purple_hold_piece0000 = "purple hold piece0000";
		public const string Purple0000 = "purple0000";
		public const string Red_hold_end0000 = "red hold end0000";
		public const string Red_hold_piece0000 = "red hold piece0000";
		public const string Red0000 = "red0000";
		public const string Right_confirm0000 = "right confirm0000";
		public const string Right_confirm0001 = "right confirm0001";
		public const string Right_confirm0002 = "right confirm0002";
		public const string Right_confirm0003 = "right confirm0003";
		public const string Right_press0000 = "right press0000";
		public const string Right_press0001 = "right press0001";
		public const string Right_press0002 = "right press0002";
		public const string Right_press0003 = "right press0003";
		public const string Up_confirm0000 = "up confirm0000";
		public const string Up_confirm0001 = "up confirm0001";
		public const string Up_confirm0002 = "up confirm0002";
		public const string Up_confirm0003 = "up confirm0003";
		public const string Up_press0000 = "up press0000";
		public const string Up_press0001 = "up press0001";
		public const string Up_press0002 = "up press0002";
		public const string Up_press0003 = "up press0003";
	}
}